import matplotlib.pyplot as plt

def calculate_power(angle):
    # Calculate power based on the angle of the side
    # You can replace this with your own power calculation function
    # This is just a dummy function for demonstration purposes
    return abs(10 * (1 - abs(angle - 0.5)))

def generate_power_graph():
    angles = [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]  # Angles representing each side
    powers = [calculate_power(angle) for angle in angles]

    # Generate a separate graph for each side panel
    for i in range(len(angles)):
        plt.plot([angles[i]], [powers[i]], marker='o')
        plt.xlabel('Side Angle')
        plt.ylabel('Power Generated')
        plt.title(f'Power Generated by Side Panel {i+1}')
        plt.grid(True)
        plt.show()

# Call the function to generate the power graphs for each side panel
generate_power_graph()

