import matplotlib.pyplot as plt

def calculate_power(side_angle):
    # Calculate power based on the angle of the side
    # You can replace this with your own power calculation function
    # This is just a dummy function for demonstration purposes
    return abs(10 * (1 - abs(side_angle - 0.5)))

def generate_power_graph():
    # Simulate the spinning of the CubeSat and calculate power for each side
    angles = [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]  # Angles representing each side
    powers = [calculate_power(angle) for angle in angles]

    # Generate the power graph
    plt.plot(angles, powers, marker='o')
    plt.xlabel('Side Angle')
    plt.ylabel('Power Generated')
    plt.title('Power Generated by CubeSat Sides')
    plt.grid(True)
    plt.show()

# Call the function to generate the power graph
generate_power_graph()

