import matplotlib.pyplot as plt
import numpy as np

# Constants
SOLAR_CONSTANT = 100  # Solar constant in W/m^2
SIDE_LENGTH = 0.1  # CubeSat side length in meters
EFFICIENCY = 0.2  # Solar panel efficiency
SPIN_PERIOD = 60  # Time for one complete spin in seconds

# Calculate solar panel area
surface_area = 6 * (SIDE_LENGTH ** 2)  # Total surface area of CubeSat
panel_area = 0.7 * surface_area  # Assumed solar panel area

# Time values
time = np.linspace(0, SPIN_PERIOD, num=1000)

# Function to calculate power output
def calculate_power(t):
    # Calculate angle of incidence based on time
    angle = (2 * np.pi * t) / SPIN_PERIOD

    # Calculate power output using the simplified model
    power = SOLAR_CONSTANT * panel_area * EFFICIENCY * np.cos(angle)

    return power

# Generate power output data
power_output = calculate_power(time)

# Plot the power output graph
plt.plot(time, power_output)
plt.xlabel('Time (seconds)')
plt.ylabel('Power Output (Watts)')
plt.title('Power Generated by Solar Panels on a 1U CubeSat')
plt.grid(True)
plt.show()
